### ISSUE TITLE
Undecipherable error message on missing CORS

### ISSUE THREAD

**Issue by kannes** [iTowns/itowns#1015]
While Chromium displays an additional error like `Access to image at 'http://example.com/3/5/0.jpg' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` other browsers like Firefox might not do so. In that case the user is left with something absolutely undecipherable like

`err http://example.com/${z}/${x}/${y}.jpg error​bubbles: false​cancelBubble: false​cancelable: false​composed: false​currentTarget: null​defaultPrevented: false​eventPhase: 0​explicitOriginalTarget: <img crossorigin="anonymous" src="http://example.com/3/6/0.jpg">​isTrusted: true​originalTarget: <img crossorigin="anonymous" src="http://example.com/3/6/0.jpg">​srcElement: <img crossorigin="anonymous" src="example.com/3/6/0.jpg">​target: <img crossorigin="anonymous" src="example.com/3/6/0.jpg">​timeStamp: 5548​type: "error"​<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … } itowns.js:5:366202`

If possible, please output a more human-friendly error messages if loading of remote resources fails due to CORS.

**Comment by zarov** [comment]
I took a look at it, and it seems I don't get the same message as you in Firefox (see below, Chrome first and Firefox second). In fact, the message in Firefox is even shorter than Chrome.

![image](https://user-images.githubusercontent.com/741255/51821880-dbf51e00-22da-11e9-96aa-f73dd2d3a6eb.png)

![image](https://user-images.githubusercontent.com/741255/51821931-01822780-22db-11e9-81b4-b59835851922.png)

Could maybe tell us more about your setup so that we may improve the logging ? Thanks !

Also please note that the first message is independent of us, as it is a browser generated message.

**Comment by kannes** [comment]
Hm, it seems like it is a mixture of CORS and mixed content (HTTP URLs in a HTTPS page)...

I made two tiles directories, one named `tiles` with a .htaccess `Header set Access-Control-Allow-Origin "*"
` inside, the other named `tiles_nocors` with no such configuration.

I then made different versions of referencing the tiles. Either relative or with explicit, absolute URLs using HTTP or HTTPS. I will remove those once we managed to close this issue for a reason or another ;)

- https://hannes.enjoys.it/carto/VIIRS_SNPP_CorrectedReflectance_TrueColor_median/globe_nocors_relative.html
- https://hannes.enjoys.it/carto/VIIRS_SNPP_CorrectedReflectance_TrueColor_median/globe_nocors_http.html
- https://hannes.enjoys.it/carto/VIIRS_SNPP_CorrectedReflectance_TrueColor_median/globe_nocors_https.html
- https://hannes.enjoys.it/carto/VIIRS_SNPP_CorrectedReflectance_TrueColor_median/globe_cors_relative.html
- https://hannes.enjoys.it/carto/VIIRS_SNPP_CorrectedReflectance_TrueColor_median/globe_cors_http.html
- https://hannes.enjoys.it/carto/VIIRS_SNPP_CorrectedReflectance_TrueColor_median/globe_cors_https.html



tile URLs  | tiles | tiles_nocors
--- | --- | ---
relative | OK | OK
HTTP | OK | FAIL
HTTPS | OK | OK

I replicated this behaviour in both Firefox and Opera (Chromium-based) so this seems by design of modern web standards. But as I noticed in the first post, Firefox does not show a browser-based console error when disregarding the non-CORS, served via HTTP in a HTTPS page. Opera does nicely.

So in Firefox all I see is lines like this: 
![image](https://user-images.githubusercontent.com/7661092/51935814-0e039e80-2407-11e9-9545-e91d9c95b1bc.png)

Maybe this is actually a Firefox bug where it *should* show an error in the console but does not? I noticed that Opera shows the network requests to the tiles as "canceled" while in Firefox they are shown as code 200 and even with preview images.

**Comment by zarov** [comment]
I can help with the message, it is generated from here: https://github.com/iTowns/itowns/blob/master/src/Source/TMSSource.js#L94-L96

What do you suggest to improve it ? We'll be very pleased if you submit a PR with an improvement !

Concerning the CORS problem, it is indeed like this by design. From what I understood, you get a 200 because the request has been successful, but having no instruction on the CORS, the server returns a 0px by 0px image, thus giving no texture but a successful request. A good resource on CORS is on MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by kannes** [comment]
Ultimately this looks like a Firefox bug to me, I have filed a (non-public) issue at their bug tracker and will report back.

**Comment by kannes** [comment]
:+1: 
I checked if I could find the issue but they deleted my account from back then. Doesn't matter :)
