### ISSUE TITLE
Stereo example is broken

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#1044]
## Context
In example `/examples/stereo.html`, when you apply effect the screen becomes black.

**Comment by zarov** [comment]
This is due to a change in THREE, as we can see here https://github.com/mrdoob/three.js/commit/d1e4dbc94020a5a5feee7871a7103016361dcd93#diff-e90339f59701d143569bb73dff9de97dL360

`WebGLRenderer.getSize()` doesn't return an object with `width` and `height` anymore, but rather a `Vector2`. Unfortunately, the current version of `THREE` we are using still returns an object. So [here](https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/StereoEffect.js#L34), it kinda breaks things (as in the `stereo` example, `renderer` is `view.mainLoop.gfxEngine.renderer`). 

An update to THREE r102 can fix this problem, and I'm pretty sure this could maybe fix other cases we haven't seen yet.

**Comment by gchoqueux** [comment]
Thanks for the diagnosis, we'll fix in **2.9.0**, with update of `THREE to r102`.
