### ISSUE TITLE
Using basic ThreeJS materials for tiles rendering 

### ISSUE THREAD

**Issue by OlegYarko** [iTowns/itowns#1181]
Hello!
 
As far as I know RawShaderMaterial is used inside  iTowns to render tiles .
It definitely gives more freedom for developers but for me writing GLSL shaders is too complicated. 

So maybe there is method to use other materials from  ThreeJS library to create stylized maps?

I thought about this feature when I noticed that the mountains do not cast shadows. After  I looked at the code I realized that  fix it not at all easy (for me).  As a solution (which does not affect the whole code) this could be a Color Layer based on Shadow ThreeJS material that is added on top of other layers.
On the other hand writing a special type of layer is probably not an easy task, perhaps there is a simpler (or not quite beautiful but working) solution how to overwrite rawshader with other threejs materials?

Thanks!
Oleg

_Here are a few examples that reveal the possibilities of using additional materials to create interesting maps and reliefs._
![terrain](https://user-images.githubusercontent.com/33403994/61363339-84e50480-a88c-11e9-8333-a650908e1de3.JPG)

![terrain01](https://user-images.githubusercontent.com/33403994/61365452-6ed94300-a890-11e9-8aaa-5dc2cb84edda.JPG)

![terrain02](https://user-images.githubusercontent.com/33403994/61365462-726cca00-a890-11e9-8c98-34ae12acbbc2.JPG)

**Comment by zarov** [comment]
> I thought about this feature when I noticed that the mountains do not cast shadows

They do not indeed. Have you tried playing with different lights of THREE.js ? If you attach it correctly to each tile, maybe it will do the job ? But I'm not very confident in this solution. You can also use a modified realistic light of the Atmosphere (you can try the current on a globe view using this: `view.tileLayer.attachedLayers[0].setRealisticOn(true); view.notifyChange();`), but I'm still not very confident if you can achieve what you're hoping for this way.

> On the other hand writing a special type of layer is probably not an easy task

It is not, because the current `RawShaderMaterial` handles both the color and the elevation, therefore if you want to change rewrite it, you will have to also modify shaders to handle this.

Anyway, while having the ability to replace the shader won't be done, the lighting as you suggested it should be a part of iTowns.

**Comment by OlegYarko** [comment]
Thank you for answer )
