### ISSUE TITLE
Feature2Texture doesn't render properly features on top of the -180/180 line of the Globe

### ISSUE THREAD

**Issue by am2222** [iTowns/itowns#1282]
Hi,
I am trying to load the following geojson file to the map but it does not render anything. 
[res2.txt](https://github.com/iTowns/itowns/files/4019621/res2.txt)

I guess the problem is with the coordinates that are not in a -180.+180 and -90,+90 but I can render the same file on google maps and cesium
Here is my layer creation
```
 var marne = new itowns.GeometryLayer('Marne', new itowns.THREE.Group());
            marne.update = itowns.FeatureProcessing.update;
            marne.convert = itowns.Feature2Mesh.convert({
                color: new itowns.THREE.Color(0xbbffbb),
                extrude: 80 });
            marne.transparent = true;
            marne.opacity = 0.7;
            // Use a FileSource to load a single file once
            marne.source = new itowns.FileSource({
                url: 'http://127.0.0.1:3000/r2.json',
                projection: 'EPSG:4326',
                format: 'application/json',
                zoom: { min: 0, max: 10 },
            });
            view.addLayer(marne);

```
## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Expected Behavior

Render a set of hexagons on the map
## Actual Behavior

Does not render anything 
## Possible Cause/Fix/Solution

Still probing

**Comment by zarov** [comment]
I managed to obtain something (by upping the `extrude` value to `10000`) and the result is the following:

![Screenshot from 2020-01-03 16-37-52](https://user-images.githubusercontent.com/741255/71732385-66c58d80-2e47-11ea-9425-5bed35174585.png)

However that's not good. The problem here is you have hexagons in the geojson, with very distant corners, and when triangulating them, the resulting triangles goes under the ground, through the globe: that's why they are not fully visible. Unfortunately, iTowns is not capable of correcting this behavior: you will need to have a more precise geojson. 

The other alternatives are to either use a `ColorLayer` instead of a `GeometryLayer` (which works, I tested it), or using a `PlanarView` (which should work).

**Comment by am2222** [comment]
@zarov wow thanks, what is difference between colorLayer and GeometryLayer? Should I change my geojson into different format? 
Actually I have to make a Tileprovider which I can read hexagons per each tile and render them. In each zoom level the resolution of hexagons also increases. So the question is, whether ColorLayer supports such tiling? something like vectortiles?

**Comment by zarov** [comment]
> what is difference between colorLayer and GeometryLayer? 

A [`ColorLayer`](http://www.itowns-project.org/itowns/docs/#api/Layer/ColorLayer) gives a layer comprised of textures, while a [`GeometryLayer`](http://www.itowns-project.org/itowns/docs/#api/Layer/GeometryLayer) gives meshes. You can see the difference between [this example](http://www.itowns-project.org/itowns/examples/#source_file_geojson_3d) (by moving the camera around to see the meshes) and [this one](http://www.itowns-project.org/itowns/examples/#source_file_geojson_raster) (which doesn't have any 3D, but it projected onto the ground).

> Should I change my geojson into different format?

No, it works as you gave it. Here is the code to try it:

```js
var marne = new itowns.ColorLayer('Marne', {
    style: {
        fill: {
            color: '#bbffbb',
            opacity: 0.7,
        },
        stroke: {
            color: 'white',
        },
    },
});

marne.source = new itowns.FileSource({
    url: 'res2.geojson',
    projection: 'EPSG:4326',
    format: 'application/json',
    zoom: { min: 0, max: 10 },
});

view.addLayer(marne);
```

> Actually I have to make a Tileprovider which I can read hexagons per each tile and render them. In each zoom level the resolution of hexagons also increases. So the question is, whether ColorLayer supports such tiling? something like vectortiles?

I'm not sure if I understand correctly, do you plan to use a subdivision with hexagons instead of classical quadrilaterals ? If so, I don't think it will work (in fact, I don't know a single framework that supports this type of subdivision ?).
Otherwise, `ColorLayer` should work correctly, as long as you are using the correct `Source`. Have a look [at the tutorials](http://www.itowns-project.org/itowns/docs/#tutorials/Create-a-simple-globe), the documentation and the [examples](http://www.itowns-project.org/itowns/examples) (with the source code) to see if you can find something that suits you. If you don't, you can still write your own Layer/Source and plug it into iTowns.

**Comment by am2222** [comment]
@zarov Hi,
Thanks for your help, I guess my issue was with defining styles. However I think there is some limitations in terms of rendering that layer. If you look at the cesium's rendering
![51434740-d857fc00-1c35-11e9-9f16-2070846821ec](https://user-images.githubusercontent.com/4707503/71829714-3feb9f00-3073-11ea-94d8-941f8986ba52.jpg)

from a similar hexagon layer there are two limitations here:
first : edges of hexagons are a bit distorted which I guess it can be neglected when the hexbin's resolution increases 
but the main issue is that it does not fully draw the poles and also the borders of the projection's limits. I mean the area when two edges of the plane join together. I guess it is because of some limitations in rendering coordinates around -90,+90(for poles) and -180,+180 (for the joining hexbins)

No actually I want to develop a tile provider similar to vectortiles but instead of pbf files I use simple geojson files.

**Comment by zarov** [comment]
> edges of hexagons are a bit distorted which I guess it can be neglected when the hexbin's resolution increases

I guess it depends on the POV and if you are close to the poles ?

> it does not fully draw the poles also the borders of the projection's limits

This is a use case we didn't test: I'm noting to fix it, thanks ! I have no date to give you unfortunately as we already have a few things to tend to.

> No actually I want to develop a tile provider similar to vectortiles but instead of pbf files I use simple geojson files.

Ok no problem, you should find what you are looking for here - minus the bugs you mentioned.

**Comment by am2222** [comment]
> I guess it depends on the POV and if you are close to the poles ?

Yes as we move close to the poles the distortions increases

> This is a use case we didn't test: I'm noting to fix it, thanks ! I have no date to give you unfortunately as we already have a few things to tend to.

Thanks. 

> Ok no problem, you should find what you are looking for here - minus the bugs you mentioned.

I was thinking to check if we change vectortilelayer parser to the geojson parser, It might work. since the structure is the same and only the files are changed. I need to do more experiments to see how that goes.
Thanks so much

**Comment by mgermerie** [comment]
Concerning the behavior at the poles : they are not usable in iTowns, due to the way the globe is subdivided around them. Supporting that is not planned yet.

I will close the issue for now, don't hesitate to open it back if it is still a current matter.
