### ISSUE TITLE
Upgrade license to CeCILL-B version 2.1+?

### ISSUE THREAD

**Issue by brylie** [iTowns/itowns#1385]
We are considering integrating iTowns into a project that is licensed as AGPL. The AGPL license was chosen since our project contains components that run only on a server and we want to preserve the users' right to access the server source code.

While iTowns uses CeCILL-B license version 1.0, this may not have strong compatibility with the AGPL (or EUPL). Later versions of CeCILL-B, namely 2.1, have improved compatibility with AGPL and EUPL licensed.

Please consider upgrading the iTowns license to include CeCILL-B 2.1 (or any later version).

**Comment by zarov** [comment]
Thanks for the suggestion ! Unfortunately, there is no CeCILL-B 2.1 license. It is either CeCILL-B (the one we are using), either CeCILL 2.1. 

The one you are interested in is CeCILL 2.1 I assume. It is a change that could be done, but we need some validation on this before doing so. We'll keep you updated !

**Comment by tbroyer** [comment]
IIRC, we dual-licensed iTowns under CeCILL-B and MIT to avoid compatibility issues with other licenses (MIT is compatible with AGPL) while still having a license under the French laws (the additional "citation" clauses were not what mattered).

IANAL but I'd say iTowns can be included in AGPL software because it is licensed under MIT.

**Comment by brylie** [comment]
OK, thanks.
