### ISSUE TITLE
Why using a more global div for controls event listening ?

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1391]
What is the purpose of cc229c95e1e1809338893b44bde076e9f0b852e3 ? 

This commit introduces bugs in one of our project ([UD-Viz](https://github.com/VCityTeam/UD-Viz/tree/master)) when updating itowns from v2.17.0 to v2.18.0 (see below for more details).

## Your Environment
* Version used: v2.18.0
* Browser Name and version: Chromium 81.0.4044.138
* Operating System and version (desktop or mobile): Ubuntu 18.04
* Link to your project: 
  * with itowns v2.18.0: https://github.com/jailln/UDV/tree/package-updates-2
  * with itowns v2.18.0 **pacthed to revert the changes of this commit**: https://github.com/jailln/UDV/tree/package-updates-2-patched-itowns

## Context
Using the viewerDiv as the div for controls event listening, inhibits some html elements (e.g. input texts) from the interface of our project.

## Steps to Reproduce (for bugs) and Behaviours

**with itowns v2.18.0:**

* Install and start:
````
git clone https://github.com/jailln/UDV.git
git checkout package-updates-2
npm install
npm start
````
* Open the following URL: http://localhost:8080/examples/DemoFull/Demo.html
* Click on the loop on the sidebar situaded on the left; a text input opens on the top-center. 
* Try to click on this text input; nothing happens while it should let you enter an adress. (note that the same issue occurs for other elements of the interface)

**with itowns v2.18.0: pacthed to revert the changes of this commit**

* Install and start:
````
git clone https://github.com/jailln/UDV.git
git checkout package-updates-2-patched-itowns
./install.sh
npm start
````
* Open the following URL: http://localhost:8080/examples/DemoFull/Demo.html
* Click on the loop on the sidebar situaded on the left; a text input opens on the top-center. 
* Clicking on thi text input now works and lets you enter an adress. (expected behaviour)

**Comment by zarov** [comment]
The idea behind it is that iTowns can add elements in the viewer div, as overlay, but those elements will need to be ignored when moving. So, that's why we move the event listeners to the viewer div. 

One of the reason behind this move is the implementation of labels (see #1303). As we are using DOM elements instead of WebGL-rendered text/icon, we can't add them to the canvas we are drawing in, so we add them under the viewer div (in multiple other div). However, if we listen to the canvas, if we click on a label, it won't do anything (no move in case for a controller, or no picking). So the suggestion was to listen to the viewer div, as we didn't expect people to do anything else in it.

Right now the solution is that you shouldn't do anything with what's inside the viewer div, and you should do all the things you wanted outside it. Note that some related-problems were fixed since 2.18.0.

If you have another idea that you find more logical, please share it, as I am always kinda lost on what to do with those problems.

**Comment by zarov** [comment]
I was thinking, instead of having the `canvas` directly under `viewerDiv`, we could create another `div` inside `viewerDiv`, that would contain all things internal to `itowns`, thus leaving the `viewerDiv` to the user.
```
viewerDiv > newDiv > canvas
```

Any thoughts on it ? (@gchoqueux as well)

**Comment by jailln** [comment]
Thanks for your quick response!

> I was thinking, instead of having the `canvas` directly under `viewerDiv`, we could create another `div` inside `viewerDiv`, that would contain all things internal to `itowns`, thus leaving the `viewerDiv` to the user.
> 
> ```
> viewerDiv > newDiv > canvas
> ```
> 
> Any thoughts on it ? (@gchoqueux as well)

I'm not an expert with on these issues either but I think its a good idea.

**Comment by gchoqueux** [comment]
```
viewerDiv > newDiv > canvas
```
This could be a solution.

We will take the time to think on a solution.

**Comment by zarov** [comment]
@jailln in the meantime, is it working if you use `viewerDiv.parentElement` to add you UI ?

**Comment by jailln** [comment]
@zarov yes it works that way, thanks.
