### ISSUE TITLE
Store DOM properties instead of access them every time in mouse events

### ISSUE THREAD

**Issue by iamvdo** [iTowns/itowns#140]
For performance reason, and [avoid reflow/repaint](https://gist.github.com/paulirish/5d52fb081b3570c81e3a), it's better to store DOM properties instead of accessing them every time.

For example, in `Renderer/ThreeExtended/GlobeControls.js`, many access to `elem.offsetTop`/`elem.offsetLeft`/`elem.clientWidth`/`elem.clientHeight`, where `elem` is the canvas element (to confirm).

**Comment by autra** [comment]
On Firefox, I have been unable to observe any reflows due to access of these properties, except for here https://github.com/iTowns/itowns2/blob/master/src/Renderer/c3DEngine.js#L31

I suppose Firefox is a bit more clever these days. We might still want to keep an eye on what happens in other browsers though.
