### ISSUE TITLE
3D canvas is inaccessible in picking event  

### ISSUE THREAD

**Issue by clementcolin** [iTowns/itowns#1478]
The release https://github.com/iTowns/itowns/releases/tag/v2.24.2 changed the height and width of the label2Drenderer <div> which now overlaps the 3D canvas. When we add a mouse down event to the window, the targeted element is the label 2D renderer div instead of the canvas (due to the Z index). This is the case even if we do not use labels in our demonstrations. Therefore, the event will never percolate to the canvas. 

Why is the label 2D renderer div always added to the viewer div by the C3Dengine ? 
Do we need to add a parent label 2D renderer div to the viewer div ? Could we not add one div per label directly as child of the viewer div ?

Environment:
* Version used: 2.24.2
* Browser Name and version: Firefox 80.0.1
* Operating System and version (desktop or mobile): Ubuntu 20
* Link to your project: https://github.com/clementcolin/UD-Viz/commit/bda246bc3052e359b2936c8a5f03b4908692435f

Note: 
We found a temporary work around by manually looking for the canvas among the label 2D renderer div siblings.

**Comment by zarov** [comment]
This is a problem indeed, but we can't change the width and height. From what I saw in your repo, I think you should change the way your `addEventListener` are declared. Instead of having `window.addEventListener`, you should have something like `viewerDiv.domElement.addEventListener`. This way, the scope is reduced to the viewer div, and you can remove the `if (event.target.nodeName.toUpperCase() === 'CANVAS')` part. Let me know if it works ! If it don't, we'll try to find a solution.

> Why is the label 2D renderer div always added to the viewer div by the C3Dengine ?

Because it is easier to do it once, than check when a new layer is added, that we need this renderer as well. Note that the render part is not done when there are no label to display.

> Do we need to add a parent label 2D renderer div to the viewer div ? Could we not add one div per label directly as child of the viewer div ?

No, it greatly impacts performance. Currently, the tree hierarchy is the best solution we have.

**Comment by jailln** [comment]
@clementcolin this should have been resolved in new itowns releases. Is it still an issue or can we close it?

**Comment by clementcolin** [comment]
This has been resolved, you can close it
