### ISSUE TITLE
Node 15 not supported

### ISSUE THREAD

**Issue by mgermerie** [iTowns/itowns#1508]
## Your Environment

* Version used: 2.26.0
* Browser Name and version: Mozilla Firefox for Ubuntu Version 81.0
* Operating System and version (desktop or mobile): Ubuntu (desktop)

## Object

Node 15 version causes issues with iTowns. The latest version iTowns support at the moment is Node 14.

## Associated PR :
#1507
#1509
These modifications allow downgrade to the previous state, where node version was the 14.

**Comment by gchoqueux** [comment]
The issue comes from [**`node-https-proxy-agent`**](https://github.com/TooTallNate/node-https-proxy-agent)

**`node-https-proxy-agent`** uses [**`node-agent-base`**](https://github.com/TooTallNate/node-agent-base)
**`node-agent-base`** fixed  [**ERR_INVALID_PROTOCOL in NodeJS 15**](https://github.com/TooTallNate/node-agent-base/pull/47)

But **`node-agent-base`** has not been updated in **`node-https-proxy-agent`**.

I build **`node-https-proxy-agent`** with **`node-agent-base 6.0.2`**, it fixes the bug.

**Comment by gchoqueux** [comment]
fixed https://github.com/TooTallNate/node-https-proxy-agent/issues/115#event-4029431290
