### ISSUE TITLE
cameraUtils.setHeading doesn't take the short

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#1517]
There is a bug in cameraUtils, if the animation between to heading isn't the short way.

You could try in console

```js
view.controls.setTilt(10)
view.controls.setHeading(-36)
view.controls.setHeading(10)
```

Could you fix this bug in other PR?

_Originally posted by @gchoqueux in https://github.com/iTowns/itowns/pull/1511#issuecomment-723922620_

**Comment by mgermerie** [comment]
By fixing this issue, I realized an interesting fact with iTowns, which is that the heading value you pass in `setHeading` are anti-clockwise counted. It means that if you request a heading of `90°`, you will be headed toward west, which usualy is `270°` in terms of navigation heading.
@gchoqueux, is this difference intended ? Or could it be changed so that the heading used with iTowns match the navigation headings convention ?

**Comment by gchoqueux** [comment]
I tkink the `globeControls` system is wrong, because the y axe is on south.
Try to activate helper in `globeControls` to verify?
May be fix it before this issue.

**Comment by mgermerie** [comment]
Thanks for the info, I shall take a look at it.
