### ISSUE TITLE
Issue in setting base_altitude for vector tiles.

### ISSUE THREAD

**Issue by biplapkc** [iTowns/itowns#1874]
I am using FeatureGeometryLayer to support building data in vector tile. I used altitudeLine function as in example, [https://github.com/iTowns/itowns/blob/master/examples/source_stream_wfs_3d.html](url) set base_altitude for the building but it is not working. Buildings are floating in air rather than extruding from  the  ground. 

In example [http://www.itowns-project.org/itowns/examples/index.html#vector_tile_3d_mesh](url) we are getting z value from the building properties and I am trying to get z value by using lat, long of the building from its property using functions getElevationValueAt but the height it is returning is not placing the building on the ground.

> var tile;
>     function altitudeLine(properties) {
>       // var coord = new itowns.Coordinates('EPSG:4326', 85.3240, 27.7172);
> 
>       // result = itowns.DEMUtils.getElevationValueAt(view.tileLayer, coord);
>       console.log("porp", properties)
>       var lat = properties.latitude
>       var long = properties.longitude 
>       var crs = properties.crs || "EPSG:4326"
>       var coord = new itowns.Coordinates(crs, long, lat);
> 
>       var result = itowns.DEMUtils.getElevationValueAt(view.tileLayer, coord)
>       return result;
> 
>     }

Am I missing something or what? Why am I having trouble in setting baseAltitude for vector laters?

**Comment by jailln** [comment]
Hi,
I've had quite a similar problem actually but I haven't been able to solve it yet. I'll let you know if I do.

Maybe @gchoqueux can help here since you recently added this part to itowns ?

**Comment by mgermerie** [comment]
Hi,
Thanks for your feedback !

Unfortunately, I did not manage to reproduce this issue with the WFS stream we use in [the WFS 3d example](https://github.com/iTowns/itowns/blob/master/examples/source_stream_wfs_3d.html). The thing is we don't have buildings coordinates in the properties. Therefore I estimated those coordinates as the center of buildings bounding boxes (which are in the properties). The method I implemented is the following : 

```js
function altitudeBuildings(properties) {
    const coord = new itowns.Coordinates(
        'EPSG:4326',
        (properties.bbox[0] + properties.bbox[2]) / 2,
        (properties.bbox[1] + properties.bbox[3]) / 2,
    );
    return itowns.DEMUtils.getElevationValueAt(view.tileLayer, coord);
}
```
instead of the already existing one : 
```js
function altitudeBuildings(properties) {
    return properties.altitude_minimale_sol;
}
```

The buildings I got as a result seamed about well positioned in altitude. There is indeed a small offset between the altitude computed with `DEMUtils` and the one read from the properties -sometimes close to 1 or 2 meters. However, this offset should result from differences in altitude computation method : as I said, i get the altitude at the center of each building's bounding box and I doubt this technique was used to compute the altitudes given in properties. 

Am I wright to assume the offset you get is significantly higher ?

If  so, would any of you have a WFS stream or Vector Tile data I could use to try to reproduce the issue ? Those data would obviously need to contain buildings coordinates in their properties.

**Comment by biplapkc** [comment]
Yes, the offset I got was significantly higher and it appears as if its floating. I am using this WFS stream/vector Tile [https://naxamapper.com/api/core/layer-tile/532/{z}/{x}/{y}/](url) You can try this to reproduce the issue.

**Comment by mgermerie** [comment]
Thanks for these data. However I was not able to find the vector tile `style` in the server. Could you please provide the json style for the vector tile data ? Or more simply the part of your code where you implement your `VectorTilesSource` ?

I have a lead on what could cause the issue. It is likely a glitch that occurs when meshes of a `GeometryLayer` are positioned -using `base_altitude` method- **before** the DEM was loaded. Therefore, the value read from the DEM with `DEMUtils` method is either : 
- the value read from a lower zoom level tile which had time to load, 
- or `0` if no DEM data had time to load on the current tile or any of its parents.

**Comment by jailln** [comment]
Hi @mgermerie ,
I don't have a public URL to share with you but I will send you the data and the instructions to host them locally by e-mail.

**Comment by jailln** [comment]
Ok I thought I had your email but I don't and it's not public on your github. Could you contact me on mine and I'll send you all this ? (if you don't have my email you can ask your colleagues, they have it :) )

**Comment by ftoromanoff** [comment]
the PR #2156 should fix that issue. Allowing the use of coord as an argument to style.base_altitude()

**Comment by jailln** [comment]
It works for me with #2156, thanks :slightly_smiling_face:

**Comment by mgermerie** [comment]
@biplapkc, #2156 was merged so it is now most likely fixed. Don't hesitate to reopen if you still encounter the problem.
