### ISSUE TITLE
2.5D 3D tiles example is down

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#1877]
The 3D tiles isn't loaded in `2.5D 3D tiles example`.

because the `Liris server` [link](http://rict.liris.cnrs.fr/DataStore/Lyon1er-2015/tileset.json) responded with a status of 503 

@ericboix and @agrignard have you an idea?

**Comment by jailln** [comment]
I don't know about the server but I can compute another tileset if this can help (similar to the previous one, but maybe on a larger zone and with textures). However where would we store it ? Is there a server for itowns demo data ?

**Comment by vladimir-rybalko** [comment]
@jailln, share your experience. With what software do you prepare tilesets?

**Comment by jailln** [comment]
I use [py3dtilers](https://github.com/VCityTeam/py3dtilers) which allows to transform citygml, obj, geojson and ifc files to 3d-tiles.

**Comment by jailln** [comment]
BTW the dataset seems to also be stored [here](https://github.com/iTowns/iTowns2-sample-data/tree/master/3DTiles/dataset-dl.liris.cnrs.fr/three-d-tiles-lyon-metropolis/Lyon_2015_TileSet)

**Comment by vladimir-rybalko** [comment]
> I use [py3dtilers](https://github.com/VCityTeam/py3dtilers) which allows to transform citygml, obj, geojson and ifc files to 3d-tiles.

@jailln, maybe you can suggest.
I'm trying to get 3D tiles to display from an obj file with a texture using py3dtilers tools. But as a result I get only one tile.
I created a [issue](https://github.com/VCityTeam/py3dtilers/issues/106) but i'm not sure if it's not on my side.

**Comment by jailln** [comment]
> > I use [py3dtilers](https://github.com/VCityTeam/py3dtilers) which allows to transform citygml, obj, geojson and ifc files to 3d-tiles.
> 
> @jailln, maybe you can suggest. I'm trying to get 3D tiles to display from an obj file with a texture using py3dtilers tools. But as a result I get only one tile. I created a [issue](https://github.com/VCityTeam/py3dtilers/issues/106) but i'm not sure if it's not on my side.

I'm not so familiar with the obj tiler of py3dtilers but I guess it depends on how your geometry is structured and how py3dtilers breaks your obj into several "features", which are then grouped by tiles. Anyway, maybe using [this option](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/Common/README.md#kd-tree-max) can fix the number of features per tile. This discussion should be continued in the issue you created in py3dtilers, since it is not related to itowns, and I'm sure the py3dtilers team will give you a more comprehensive answer :)

**Comment by EricBoix** [comment]
@gchoqueux Concerning the broken link, this is our bad ! We moved away all our
stable/shared tilesets from our project level server `rict.liris.cnrs.fr` to a more 
stable/permanent laboratory level server `dataset-dl.liris.cnrs.fr`. And we forgot
to inform our data users. Although we made this move quite some time ago, the 
`rict.liris.cnrs.fr` virtual machine host was only (automatically) turned off this summer.
Again, our bad, and sorry for not warning you guys.
 
Anyhow if you replace the original link 
   `http://rict.liris.cnrs.fr/DataStore/Lyon1er-2015/tileset.json`
with 
   `https://dataset-dl.liris.cnrs.fr/three-d-tiles-lyon-metropolis/2015/Lyon-1_2015/tileset.json`
the 3DTiles example should work again smoothly.

By the way, feel free to copy and host this tileset on some servers of yours
in order to avoid this dependency and any further surprise (this data as an
[ETALAB](https://dataset-dl.liris.cnrs.fr/three-d-tiles-lyon-metropolis/ETALAB-Licence-Ouverte-v2.0_EN.pdf) license.

Although  hopefully the lab level `https://dataset-dl.liris.cnrs.fr/` server should have a much longer time span.
