### ISSUE TITLE
Impossible to go to level 20 of tilematrix using a WMTS

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#188]
It seems that it never go after zoom level 19 using a WMTS even with tileMatrixSetLimits specified with a 20 level

**Comment by peppsac** [comment]
Subdivision level is limited in quadtree, see : https://github.com/iTowns/itowns2/blob/master/src/Scene/Quadtree.js#L50

**Comment by nosy-b** [comment]
Ok.
Shouldn't that max subdivision model be ajusted to the max of TileMatrixSet?

**Comment by peppsac** [comment]
I don't think so because a user may want to limit geometry subdivision regardless of available texture levels.

But the max subdivision setting should be moved out of Quadtree, probably in the layer (https://github.com/iTowns/itowns2/blob/master/src/Core/Commander/Interfaces/ApiInterface/ApiGlobe.js#L242).

And this layer should also be moved out of ApiGlobe, probably to `index.html` like all other layers :)
