### ISSUE TITLE
Bad handling of wmts layer boundaries when mixing them. (Test with world DTM)

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#192]
I added in the index an elevationLayer for the whole world and an elevationLayer for high precision DTM just for France.
- The order of declaration of the elevation layers is important. (But we wish to have an automatic use of the best precision layer available at any position)
- The update strategy group has to be the same for both even though one has less levels than the other.
- Test on tileMatrixSetLimits is not done (minTileRow etc). And even if it was, no country is squared. On the boundary we usually meet Tiles with NoDataValue and no tiles available.
- Same problem as already mentioned(#191). If deactivated layers (imagery) it can still try in some case to request them and end up to too many bad requests.

Two big use cases: 
- Evolving around the Alpes. It works fine with no break now, but when zooming more out of France it tries to download HighRes French DTM.
- Deactivating all imagery Layers but Ortho, then go to Everest Mountain, it dies on trying to download many tiles of deactivated imagery layers (not available out of France)

~The Branch for those tests is [https://github.com/iTowns/itowns2/tree/worldDTM](https://github.com/iTowns/itowns2/tree/worldDTM)~

I 'm going to work on this (starting by handling deactivated imagery layer as discussed in #191) but as you did some work on it recently @peppsac , @gchoqueux , don't hesitate to look too.

**Comment by peppsac** [comment]
My 2 cents:

> The order of declaration of the elevation layers is important. (But we wish to have an automatic use of the best precision layer available at any position)

Yes because itowns can only use 1 texture for elevation, so higher priority layer should be listed 1st.
What do you have in mind to fix this?

> (not available out of France)

It shouldn't try to download them if the layer had a proper bounding box (instead of simply relying on the tile.level).
Also note that I have a set of commits to handle error properly - with the default strategy being: 3 retries then stop trying to download a texture.
See https://github.com/iTowns/itowns2/pull/141/commits/4469b742bfee58bf1bd07fdc005817a5921efaa3 and https://github.com/iTowns/itowns2/pull/141/commits/2cb7c59db2547354b3aa0b1e99eacc1a8dca870a
