### ISSUE TITLE
iTowns view traps keyboard events even if the view div is not focused

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1931]
## Your Environment
* Version used: v2.38.2
* Browser Name and version: firefox and chrome
* Operating System and version (desktop or mobile): ubuntu, windows
* Link to your project: x

## Context

When using itowns in a window with other elements (a form in this case), I noticed that using some keyboard keys such as arrows, ctrl and shift moves itowns view even if the div containing the view is not focused. 

## Steps to Reproduce (for bugs)
1. Create a page with an input and a div containing itowns view
2. use ctrl + arrows in the input

## Expected Behavior
The view doesn't move since the user is focusing the input.

## Actual Behavior
The view actually moves

## Possible Cause/Fix/Solution

This happens because itowns traps events from the window and not from the viewer div, originally set like that for a specific usecase where it was more comfortable to always have itowns view focused. In my opinion itowns shouldn't watch keyboards events on the window because it reduces its possible integration in other softwares. I propose to change this behaviour and to watch events on the viewer div. @mgermerie what's your opinion on that?

**Comment by mgermerie** [comment]
Indeed, we could listen for keyboard events on `view.domElement` instead of `window` to enhance integration. This would include minor changes in most of the [control files](https://github.com/iTowns/itowns/tree/master/src/Controls).
The only thing that should be checked is with `Labels` : we would need to be sure that each label's `domElement` keeps focus on the view's `domElement` when clicked, but that is not too big an issue.
