### ISSUE TITLE
Extract widgets to another repository?

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#1986]
I think widgets should be extracted to a different repository so they can have their own lifecycle. It would also make the separation between the core lib and the widgets clearer. WDYT @mgermerie @gchoqueux @ftoromanoff ?

**Comment by mgermerie** [comment]
I agree with that, it would allow to have a widgets repository storing a wide variety of generic widgets users could chose from. Adding new widgets to that repository would not impact iTowns (at least theoretically, since often times creating a widgets needs to expose some methods in iTonws sources).

However, this raises a question about widgets documentation : should it be kept in iTowns documentation or should it be in a separate documentation ?

**Comment by jailln** [comment]
In my opinion the documentation should be in the repository holding the widgets so the separation is clearer.
However, we must expose the widgets repository (through links in the README and on itowns documentation and example pages) to let users know that it exist. Also, we should then update the website so it exposes itowns and itowns-widgets.

**Comment by jailln** [comment]
Closing since we went further on this subject in discussion #2061
