### ISSUE TITLE
Zoom in and out at the cursor position instead of the center of the canvas

### ISSUE THREAD

**Issue by LoicUTC** [iTowns/itowns#2011]
I propose to develop the ability to zoom in and out from the cursor position because is more common (OpenLayersn Cesium) and seems more natural to me than from the center of the screen.

**Comment by alexLuky** [comment]
The same for the camera rotation.... Current ORBIT rotation always around the screen center. 

Another not usefull behavior it's when you're near the ground and trying to pan a little forward you can catch the point that is near the horizont and camera flys away to the horizont. It happens because of raycast to the Globe mesh.
