### ISSUE TITLE
ghpage and gh-pages & gh-pages not updated

### ISSUE THREAD

**Issue by vcoindet** [iTowns/itowns#203]
There are two gh-pages that might be in conflict.

**1 - gh-page:** 
This one is the original one (I think)
It's related to the demo website (http://www.itowns-project.org/itowns2/), but the demo website is not updated, same thing for the API documentation (http://www.itowns-project.org/itowns2/API_Doc/) where we should find the documentation of the function _setZoomLevel()_ (for example), but it's not the case...

**2 - ghpage:**
**What is this one ?**
It looks like it's a clone of the master...

**So my point is:** 
The autodeploy.sh is supposed to deploy **dist**, **index.html**, **API_Doc**, and **examples** in gh-pages so the demo is always updated.
But it seems that none of the last PR merged in the master (#194 and #197) were deployed correctly in the gh-pages branch as none of  **dist**, **index.html**, **API_Doc**, and **examples** are updated in here...

Why the last modifications are not in the demo website/gh-pages ? I think something went wrong but I don't understand what...

**Comment by tbroyer** [comment]
Regarding `gh-pages`, there are jsdoc errors preventing the "deployment": https://travis-ci.org/iTowns/itowns2/jobs/174826498#L481
Because it's an `after_success` it does not affect the build result.
We may want to migrate to a `deploy`: https://docs.travis-ci.com/user/deployment/script and/or do the jsdoc during the build phase.

As for the `ghpage` branch, GitHub tells me (from my dashboard) that @gchoqueux created it 3 days ago (on 2016-11-11T11:58:27Z exactly)

BTW, we're still running Travis on Node 4 and 5; shouldn't we update to 6 and 7?

**Comment by vcoindet** [comment]
OK, I couldn't find the travis log (#jobs965.1) until you post it here. 
I found the error, it seems that jsdoc doesn't support "<type>", I will correct it (the error is in ApiGlobe.js, as expected).

For the other points you describe, we should probably discuss it with the PSC. What do you think @gchoqueux @vpicavet @nosy-b ?

**Comment by vcoindet** [comment]
Doc corrected in PR #204

**Comment by tbroyer** [comment]
Updating Node.js and "linting" the JSDoc as part of `npm test` in PR #206
