### ISSUE TITLE
[BUG - ColorLayer] ColorLayer rendering issue on firefox with planar view

### ISSUE THREAD

**Issue by ketourneau** [iTowns/itowns#2236]
## Your Environment
* Version used: 120.0.1
* Browser Name and version: Firefox
* Operating System and version (desktop or mobile): macos (sonoma)
* Link to your project: [github source code](https://github.com/bloc-in-bloc/itowns/blob/7ff1ea45c00d2052b2b1e436b6bf71f2eafdc117/examples/demo_hackathon_orvault_planarView.html#L283)

## Context

We used a WMS source (to render a GeoTiff) with a ColorLayer and a PlanarView and with map background. 
We want to replace white color of WMS source by transparency so we try to use `effect type:2` on ColorLayer ([applyWhiteToInvisibleEffect](https://github.com/iTowns/itowns/blob/6737c930764c721d2770025f6da76e9ade67f6e8/src/Renderer/Shader/Chunk/color_layers_pars_fragment.glsl#L75)).
But it seems to render black color in firefox so we apply `custom effect type`.

## Steps to Reproduce (for bugs)
[online demo](https://demo-hackathon.netlify.app/examples/demo_hackathon_orvault_planarview.html)
1. Use firefox and open online demo link
2. Expand Color Layers and expand GeoTiff layer
3. Set effect_type to 2 ([applyWhiteToInvisibleEffect](https://github.com/iTowns/itowns/blob/6737c930764c721d2770025f6da76e9ade67f6e8/src/Renderer/Shader/Chunk/color_layers_pars_fragment.glsl#L75))

## Expected Behavior
With effect_type:2 on ColorLayer => white color must be invisible (on all browsers).

<img width="1512" alt="firefox_effect_type_custom" src="https://github.com/iTowns/itowns/assets/39763266/16414875-8381-4f62-a1db-ce769a068aa2">

## Actual Behavior
With effect_type:2 on ColorLayer => white color is replaced by black color (only on firefox, it's working on chrome).

<img width="1512" alt="firefox_effect_type_2" src="https://github.com/iTowns/itowns/assets/39763266/40db5097-443b-4990-b440-58ea988c406d">

## Possible Cause/Fix/Solution
It seems it's caused by [applyWhiteToInvisibleEffect](https://github.com/iTowns/itowns/blob/6737c930764c721d2770025f6da76e9ade67f6e8/src/Renderer/Shader/Chunk/color_layers_pars_fragment.glsl#L29).

I think we can replace [line 29 ](https://github.com/iTowns/itowns/blob/6737c930764c721d2770025f6da76e9ade67f6e8/src/Renderer/Shader/Chunk/color_layers_pars_fragment.glsl#L29) by `color.a = 0.0`.

It's how we fix it [in our demo](https://github.com/bloc-in-bloc/itowns/blob/7ff1ea45c00d2052b2b1e436b6bf71f2eafdc117/examples/demo_hackathon_orvault_planarView.html#L271C38-L271C38).

**Comment by Desplandis** [comment]
Hi and thanks for your detailed bug report!
I managed to easily reproduce this issue and agree with you on the cause of the bug.

The different type of effects on color layers are clearly not well-documented (especially the `effect_parameter` layer property which is passed to the shader as a per-layer uniform).

In the case where `effect_type = 2`, `effect_parameter` is passed as the `intensity` parameter of `applyWhiteToInvisibleEffect` and is used in [line 29](https://github.com/iTowns/itowns/blob/6737c930764c721d2770025f6da76e9ade67f6e8/src/Renderer/Shader/Chunk/color_layers_pars_fragment.glsl#L29). Since we do not set a default value to `effect_parameter` it is passed as `undefined` to the shader (which could be implementation-defined behavior).

Moreover, I too question the need for [line 29](https://github.com/iTowns/itowns/blob/6737c930764c721d2770025f6da76e9ade67f6e8/src/Renderer/Shader/Chunk/color_layers_pars_fragment.glsl#L29) since $a \in [0.99, 1.0]$ at this point. Since this is not documented, we could either:
- set the opacity to 0.0
- factor the opacity by the intensity

I'll open a PR fixing those three issues (documentation, undefined and shader code)!
