### ISSUE TITLE
[BUG - WMTS] WMTS with PlanarView 

### ISSUE THREAD

**Issue by ketourneau** [iTowns/itowns#2240]
## Your Environment
* Version used: 2.4.1.1-next.9
* Browser Name and version: Firefox
* Operating System and version (desktop or mobile): macos (sonoma)

## Context
We try to use a WMTS source with PlanarView and it doesn't seem to work properly.
The source doesn't seem to take view extent into account.

## Steps to Reproduce (for bugs)
Replace `wmsImagerySource` and `wmsImageryLayer` from `view_25d_map.html` by :
```
itowns.Fetcher.json("./layers/JSONLayers/Ortho.json").then(
    function _(config) {
        config.source = new itowns.WMTSSource(config.source);
        var layer = new itowns.ColorLayer("Ortho", config);
        view.addLayer(layer);
    }
);
```

## Expected Behavior
![Capture d’écran 2023-12-13 à 09 07 44](https://github.com/iTowns/itowns/assets/39763266/1a1ccb4e-ac42-4fec-af02-1ecf204c0dff)

## Actual Behavior
![Capture d’écran 2023-12-13 à 09 08 21](https://github.com/iTowns/itowns/assets/39763266/7db84757-9a02-486d-95b1-5fe01a289313)

**Comment by AnthonyGlt** [comment]
Hello, thanks for this feedback
It's the expected behavior on iTowns, the WMTS requests are based on the zoom level so the all the source tiles will be displayed on the entire extent as a level 0. I don't know if it's the good way to go because we ignore the coordinates parameter, this behavior could be changed if it doesn't meet the necessities of the users. 
We are going to check if it can be implemented differently.
Do you have an example of your expected behavior ? Is it like that on openlayer ? If so, we will check that.

**Comment by ketourneau** [comment]
Thanks for your reply and thanks for the WMTS clarification.
We can stay with a WMS source in our case, which already works very well.

We have found an example of using WMTS in another solution (Microsoft.Maps.Unity) if it's can help for thinking https://github.com/bloc-in-bloc/MapsSDK-Unity/blob/custom-map-provider/SampleProject/Assets/Microsoft.Maps.Unity.Examples/CustomMapExample(IGN)/Scripts/WMTSTileLayer.cs

We consider the subject closed because it's work with WMS source.
