### ISSUE TITLE
Split non-generic parts of iTowns into specific repositories

### ISSUE THREAD

**Issue by vpicavet** [iTowns/itowns#242]
Given the following context, we want to split the current repo into various repositories, keeping the core of the framework in itowns2 and the client parts in other repositories.

- We want to release version 2.0 as soon as possible
- itowns2 should remain a generic library and be usable in various use cases
- Once version 2.0 has been released, it will be difficult / not possible to break the API
- Maintainance will be key later on, we should therefore build on stable foundations
- We want a separation of concern between core components and client-oriented components ( e.g. widgets)

Therefore, this proposal is to keep the most stable part of iTowns into the itowns2 repository, and move what is not generic enough, or what is not stable enough in separate repositories. 

This will not prevent from re-entering parts into itowns2 core later. The opposite is much more difficult ( removing parts from core after 2.0 release ).

The first separate repository would be itowns-geoportal, containing everything specific to the geoportal use case.

See #221 for related discussion, as well as #241 

Please comment on this issue ASAP before we move to implementation.
@tbroyer @nosy-b @autra @gcebelieu @elias75015

**Comment by autra** [comment]
I'm in favor of this architecture : geoportail team will be able to go forward with their needs, and itowns "core" will have time to build a clean and generic interface without worrying to slow down or break itowns-geoportail. The idea is to work in collaboration with the geoportail team, in order to adapt `itowns-geoportail` as we clean itowns2.

To move forward, I have created https://github.com/iTowns/itowns-geoportail (we can still move/delete/recreate this if needed). Please note that the above repo will not work until a first `0.0.0-alpha` is published to npmjs. For this, I'm waiting for your comments :-). 

If you still want to test the above repo, just change the `"itowns": "^0.0.0-alpha"` line to point to your itowns2 repo locally on [this branch](https://github.com/autra/itowns2/tree/geoportail-npm)).

**Comment by gcebelieu** [comment]
> -    We want to release version 2.0 as soon as possible
> -     itowns2 should remain a generic library and be usable in various use cases
> -     Once version 2.0 has been released, it will be difficult / not possible to break the API
> -     Maintainance will be key later on, we should therefore build on stable foundations
> -     We want a separation of concern between core components and client-oriented components ( e.g. widgets)

OK with that approach, but the point is what goes where ?

* Widgets that iTowns assumes to be part of its own may be put in a src/widgets (for instance) directory (see : what [Cesium](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Source) does), I suggest others goes in examples/ sub directories
* Where does external API (#62) goes ? Given the list : to me, the major part goes to iTowns core (events, methods, ...) because this is the API, except widgets list for which some will go in iTowns widgets directory or not (given what is said above)

> The first separate repository would be itowns-geoportal, containing everything specific to the geoportal use case.

well, again, what is specific to the geoportal use case and what is not ? To me what is specific and not assumed to be part of itowns should not be in iTowns core or widgets and rather in a  geoportal sub repository of examples (for instance).

**Comment by vpicavet** [comment]
Yes, the question of what goes where will always be important and present.

The 2.0 release and the fact that it is much simpler to add things afterwards than remove or change existing things in itowns core, leads to a strategy of moving things out, and eventually moving them back once we are sure they are stable and generic enough.

**Comment by nosy-b** [comment]
Ok, this seems to be an important debate :)
We all agree iTowns2 should be compact, generic and stable meaning it should not be dedicated to any specific visualization client. 

But we should keep in mind that not only developers will use it but also non-coder user. So having a core version doesn't forbid to have a basic friendly-user interface sample in _Example_ directory.
That beeing said, the first large client that will use itowns is the French Geoportal. So they should have their own depo _itowns-geoportal_ where they import itowns2 and create their own specific interface/widget, easy to implement as itowns2 has a high level API. The itowns2 API is key here.

**Comment by gcebelieu** [comment]
In fact, we already have a repo in which we will create our specific widgets :

https://github.com/IGNF/geoportal-extensions

It will lead to a new "Geoportal extension for iTowns" sub project.

As far as I understand the new itowns-geoportal repository would serve to host existing (or being developed) code that has not be accepted (but might be) in iTowns2 ?

**Comment by vpicavet** [comment]
Agree that the API is important, and it will evolve, but if we want to avoid technical debt in the future, we should only keep in version 2.0 what is truly stable and generic enough.

@gcebelieu yes, exactly

**Comment by autra** [comment]
> As far as I understand the new itowns-geoportal repository would serve to host existing (or being developed) code that has not be accepted (but might be) in iTowns2 ?

Yes, also allowing faster development workflow on your side, as you won't need to worry about coding standards of itowns (linter, and testing...), backward compatibility issues and having a stable API, all things that are always a concern for a (viable) open-source framework.

**Comment by nosy-b** [comment]
Ok ,
So to sum up and conclude this issue:

- iTowns release 2.0 will not have core functionnalities handling widgets
- iTowns r2.0 repo has a few examples of code, some of them might exposee widget to control the camera for example.
- Geoportal has its own repo to handle widget and interface.
- IPR should be handled by iTowns r2.0 core but at a minimal level -> iTowns r2.0 API should give access to the current visible layers (absolute need for many uses) so will also give at the same time the IPR credit _string_ as it is an attribute of the layers
