### ISSUE TITLE
3dtiles setting scaling is invalid

### ISSUE THREAD

**Issue by liangyuan1** [iTowns/itowns#2429]
How to scale the model and modify its position on the map while automatically switching the perspective to the position of the model after changing the scaling ratio, which causes the model to be lost after converting manual modeling data into 3dtiles for loading
## Your Environment

* Version used:2.44.0
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:
## Scale not set
###code
  view.addLayer(layer).then((layer) => {
    zoomToLayer(view, layer)
  })
### result
![image](https://github.com/user-attachments/assets/d52ac181-442e-4280-a182-8fea96dc4787)

## Scale set
###code
  view.addLayer(layer).then((layer) => {
    layer.object3d.scale.set(3, 3, 3)
    layer.object3d.updateMatrixWorld()
    zoomToLayer(view, layer)
  })
### result
![image](https://github.com/user-attachments/assets/dc7120a4-d0c6-4441-b693-61f797a14647)

**Comment by jailln** [comment]
Hi, thanks for reporting this issue.

Scaling the group does not work indeed. However, scaling the tiles when they are loaded does work:

```
  layer.addEventListener('load-model', (m) => {
      m.scene.scale.set(2, 2, 2);
      m.scene.updateMatrixWorld();
  });
```

My guess is that it's because the group is positioned in (0,0,0) and the tiles are positioned on the globe, so scaling is applied relatively to the position of the group (instead of the tiles position) which messes up the tileset position.

I'll close this since I provide a workaround and 3D tiles are generally already scaled and positioned correctly so I don't think we should provide a specific API to help for scaling (or rotating) them. However, feel free to reopen it if needed. cc @Desplandis too.
