### ISSUE TITLE
Trouble using itowns as a dependencies

### ISSUE THREAD

**Issue by ClementBouche** [iTowns/itowns#247]
I add itowns dependency to my AwesomeProject.
Here the package.json file :  
```javascript
{
  "name": "AwesomeProject",
  "dependencies": {
    ...
    "itowns": "git+https://github.com/iTowns/itowns2.git#WFS2_rebased"
  },
   ...
  "scripts": {
     ...
  }
}
```

Npm load the itowns project but don't compile it. So no dist/itowns.js :(
Is it possible to add 'postinstall' command to build the project ?

My current solution is to embed dist/itowns.js file in a fork. See :
https://github.com/ClementBouche/itowns2/tree/WFS2_rebased

**Comment by vcoindet** [comment]
@autra @tbroyer @nosy-b @gchoqueux 

What do you think ?

**Comment by autra** [comment]
Hi @ClementBouche! Thanks for using itowns :-)

Currently, installing from a github branch is not supported. So I guess you can either:
1. do what you have done already, ie forking.
2. clone the repo locally, run `npm pack` in it, and `npm install <generated_archive>` in your client repo, (so you don't need really need to fork if you only need itowns locally).

That's definitely something I would like to support in the future, but I'm not sure how to do it properly yet. The think is that `postinstall` script is run whenever the user `npm install` the package, even if it comes from npm and so already has the `dist/` folder and stuff.

Btw @tbroyer do you have an idea for this use case?

**Comment by ClementBouche** [comment]
Thanks for the reply @autra !
The first solution satisfies me.

Could it be a generic solution ? Could you push dist/itowns ?

**Comment by tbroyer** [comment]
I, for one, really hate committing build artifacts; for many reasons: first, build tools and package registries are there for a reason, then as soon as you `npm run build` you'll have modified files in your working directories and run the risk of committing them by mistake and/or have to live with the "noise"; then either you take care of always keeping them up-to-date (either manually, then polluting code reviews, or automatically through Travis for instance, then polluting the commit history), or you update them once in a while and then no-one will be able to tell exactly which commit of `src` the `dist` corresponds to. Not to mention the added bloat in the Git repository size (even if relatively small in our case, when you add compression and packing).

Now, because the `gh-pages` is updated automatically by our Travis build with the `dist/` folder already, maybe we could copy the `package.json` there in addition, so at least you could easily depend on the "latest snapshot".

Other than that, I think that if you want to work with a specific branch (which will likely be an ephemeral feature-branch), you should clone the repo locally and then either `npm pack`+`npm install <tarball>` regularly, or `npm link`+`npm link itowns` for "live updates".

**Comment by autra** [comment]
totally agree on @tbroyer on this one. @ClementBouche could you live with that until this branch is merged? Then we'll release another version on npm and you would be able to use that.

**Comment by ClementBouche** [comment]
Thanks for your reply @tbroyer and @autra.
No problem to go with a fork for me. I close this issue, now it's related to :
https://github.com/iTowns/itowns2/issues/122
