### ISSUE TITLE
API Discussion for release candidate

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#272]
Hi all!
Here we can discuss on the API aspect of iTowns before launching the release candidate
It seems we don't all (developers) have the exact same point of view,  for now :)

- As for now, iTowns leave access to a large part of the code as methods are usually not private. -> not good
- High level API is too messy and not generic enough. -> not good

We need to agree on the methods available from the API, usable for non professional users and coders but also protect method that should not be accessible directly.

**Comment by peppsac** [comment]
My proposal:
- for each class/object/file of iTowns: use `_` prefix to indicate private code. Or even better, make it private to the file (= do not `export` it and do not make it a method of an exported object)
- all the other code should be documented, and exported in `Main.js`
This is the API of iTowns (exposed classes and their members, except those prefixed by `_`).
This is exactly what `three.js` or `Cesium` are doing.


Regarding the notion of "high-level" API: we can't write a "high level" API that covers all users use case, because iTowns is a framework, not a "SIG-engine" or a utility lib (like `proj4` for instance).

But we can also expose some helper|utility|high-level code.
For instance, a `new itowns.createGlobeViewer()` that would implement the plumbing required to display a globe using itowns.
The returned object could also have a methods that are globe specific (`pickOnEllipsoid` for instance).
All this code would be written using the exposed API mentionned earlier.

See https://mollyrocket.com/casey/stream_0028.html for a really good video on API design.

**Comment by gcebelieu** [comment]
> *    for each class/object/file of iTowns: use _ prefix to indicate private code. Or even better, make it private to the file (= do not export it and do not make it a method of an exported object)
> *    all the other code should be documented, and exported in Main.js
>     This is the API of iTowns (exposed classes and their members, except those prefixed by _).
>     This is exactly what three.js or Cesium are doing.


I agree with that. The point is on the *documented* thing : for the moment it seems that only Methods and objects exposed by ApiGlobe are documented and lead to a user oriented documentation exposed here : http://www.itowns-project.org/itowns2/API_Doc/ 

My opinion is that each function / class / events that are exported (and then take part of the API) should be documented at least by public JSDoc. This is a necessary step in the releasing process.

Regarding the existing "HighLevel" API, it has the advantage of exposing functionalites to external users (I'm part of them) otherwise I don't know how to use it. If a functionnality is already implemented by an internal object that can be exported, it is certainly more pertinent to export that object.

The discussion may focus on how to make existing API fit with core objects that could take part of the public API by being exported.

**Comment by elias75015** [comment]
As asked, see below the list of events we would like to be provided in the API (needed by geoportail) : 

**Global**
- globeloaded (when the viewer is totally loaded, and ready to be used)

**Camera / View events :**
- centerchanged (when the point aimed by the camera changes)
- zoomchanged (when the distance between the camera and the aimed point changes)
- orientationchanged (when the orientation of the camera changed, tilt or heading)

**Data Layer events :**
- layerchanged (when a visible/opacity/index property of a data layer changes)
- layeradded (when a data layer is added to the viewer)
- layerremoved (when a data layer is removed from the viewer)

Of course, the names of these events are not definitive, but we absolutely need to detect when those events are triggered in order to develop our iTowns Widgets. 

When triggered, these listeners have to return the old value of the changed property.

See issue #105 and PR #269.

**Comment by autra** [comment]
Roger that! 

One question:
 
> globeloaded (when the viewer is totally loaded, and ready to be used)

Do you want an event when the user can interact, or when the initial view is completely loaded (all the tiles of initial level are loaded and visible)? The interaction is possible before everything is loaded, for information.

**Comment by elias75015** [comment]
I think it should be triggered when the interactions on the map are possible. The use case is : as soon the map/globe/viewer is loaded, the user interacts with; it doesn't matter if all the initial tiles are loaded or not.

**Comment by gchoqueux** [comment]
**Architecture way to beta/Rc version**

* Main objective is to remove ApiGlobe
  * Move the api's functions in the core
  * Rename `Scene` to `iTowns`
  * The functions will be placed in objects of the same scope
     * all functions `add..Layer`, `get..Layer`, `remove..Layer` and `move..Layer` to `iTowns` or `SceneConfiguration` object
     * all functions to `set/get camera transformation`  in `CameraControls/GlobeControls` (if auto update `cameraControls` mechanism is added in `iTowns/Scene` when all new `datas/items` are loaded)
  * fusion `layersState` and `layerTrees`, which will be called `items`
* Events management

I am to keep `SceneConfiguration` that represents geographic `data/process` to be clearer. 
I also propose to rename it in `Atlas` that makes sense with `items`. 
In the logic of placing functions in objects of the same scope, the functions `add..Layer`, `get..Layer`, `remove..Layer` and `move..Layer`  should be placed in `Atlas`.

**Comment by autra** [comment]
Also:

* Check the visibility of exposed modules and functions, and properly hide them if needed
* update the doc of exposed function, and generate it for all of them, not only for ApiGlobe.js
* Make itowns instanciable several times in a webpage.

**Comment by autra** [comment]
Also: 
- rework the fiddle embedded in doc: they (at least some of them) currently refer to a (very) outdated itowns2.js in mbredif github.io page... They should all refer to itowns.js is our gh_pages.

**Comment by vcoindet** [comment]
> rework the fiddle embedded in doc: they (at least some of them) currently refer to a (very) outdated itowns2.js in mbredif github.io page... They should all refer to itowns.js is our gh_pages.

Done, all JSFiddle examples embedded in the doc refer now to itowns.js in our gh_pages.

**Comment by autra** [comment]
@vcoindet the url is in https, but the certificate is not valid. You might already have added the certificate in your browser, but for lambda people, this won't work. Could you go back to http url please?

**Comment by vcoindet** [comment]
@autra : all done !
