### ISSUE TITLE
Add a createGlobe API to pass an existing Three.js scene

### ISSUE THREAD

**Issue by mattrei** [iTowns/itowns#278]
Hi,

I am totally impressed by the itowns2 globe example and the API in general. Looks wonderful to me.

However I have one design request. I would like to use the globe example on an already defined THREEJs Scene. Currently the `createSceneGlobe`? API expects a _div_ and creates the renderer and scene itself.
I think it is a great idea to also have `createGlobe` API where I can pass a `scene` object myself.

Having a quick glance at the well structured source, it may be possible to add feature without having a big impact on the code. 

What do you think about it?

Thx,
Matthias

**Comment by gchoqueux** [comment]
Hello
Very pleased that you like it.

For the moment, it is not possible to create a globe alone. There is a specific scene graph path in our API. Maybe we will later merge the two scene graph paths.
In any case it will not be possible in the first release.

But soon there will be tools to integrate your own 3D objects.

**Comment by autra** [comment]
Hey @mattrei, it sounds very interesting! Can you tell us a bit more about your use case? Let us see what we can do for you!

**Comment by mattrei** [comment]
hi  @gchoqueux  and  @autra,
thanks for the interest!

My use case is quite simple: I am currently developing for my thesis an educational web application, where pupils can interact with a globe. Currently my globe, and thats fine for the requirements so far, is quite static. As everything is developed in Three.js my globe is visually just a sphere with a earth like texture popped on it.

However your example impressed me quite a bit, because its basically a Cesium3D globe, built on the Three.js stack. The Cesium3D globe is not compatible within Three.js.

That said, it would be great, probably for many applications, not just mine, to have an interactive globe as provided in your examples, where you users can zoom in and zoom out accordingly and the raster tiles get updated accordingly. 
However It just can't use a Three.js scene provided by you, however I would love to have a way to add the globe as an Object3D to my scene.

Hope I could clarify my use case.

Thx for your efforts and interest!

**Comment by gchoqueux** [comment]
Sure enough it would be nice if we can add the globe to a scene three.js.
But this isn't foreseen in the first release. On the other hand we will quickly propose tools to add objects to the ground.

> However It just can't use a Three.js scene provided by you

Why?

**Comment by autra** [comment]
@mattrei you can already get a ref to the THREE js scene we instanciate with `itowns.viewer.scene.gfxEngine.scene3D`. Also, the scene is instanciated in `c3DEngine.js`, maybe it's not that hard to patch itowns to pass an already instanciated scene to c3DEngine.

Also if you use a module bundler like webpack and get itowns via npm, you can import or require THREE js directly in your code, which would allow you to create Object3D using the same THREE.js instance as we do.

So to summarize, you have 2 choices:
- use our scene. You need to use a module bundler and npm. You need to depend on the same version of THREE.js as we do (but that's to be expected). You are also dependent on the way we instanciate it though.
- use your scene. You need to patch itowns for that. So that's the most flexible path, but also the most dangerous, as  the code currently does a lot of assumptions about this scene.

Ok it's not very convenient at the moment, I know. I hope we will manage to make things easier in the near future for this use case.

**Comment by peppsac** [comment]
@mattrei can you give a try at the PR #308 ?
I'd love to know if it helps you with your use case. Thanks!

**Comment by mattrei** [comment]
@peppsac thanks for the PR.
yes much better, it shows the globe in my scene. (There is still the dependency on the viewerDiv DOM node that can be probably easily "removed").

However the main issue I am having right now, is the ThreeJS Camera instance. So in my use case I also would need to pass a camera instance to itowns and not let one create it by themself. Do you think that is possible in the current architecture?

Thx!

**Comment by peppsac** [comment]
You can abuse the API and replace the camera with yours:

```js
view.camera.camera3D = your_camera;
```

But soon the `options` field of GlobeView will allow to pass your own camera and to disable default controls if you don't want them.

**Comment by mattrei** [comment]
I am looking forward to this new API!

**Comment by zarov** [comment]
If I'm not mistaken, this issue seems solved ?
