### ISSUE TITLE
New UML Diagrams

### ISSUE THREAD

**Issue by vcoindet** [iTowns/itowns#322]
As the old UML digrams are not available on the wiki now (which is a good thing as they were deprecated), it would nice to create new ones to describe the architecture of the project. I think it would be benefic for the release ! 
And as we have now two modes (planar and globe), I think it would be benefic for developpers to see what's in common in both of them.

As the project is well advanced today, maybe we could generate some UML diagrams from the code as a starting point. 
I found [JS/UML](http://jsuml.sourceforge.net/) plugin which seems to be working on Eclipse IDE, we are trying to make the install to see the result right now.

But does any of you have an idea of other plugins we could use to create UML diagram from the code ?
Or maybe any of you has already adressed himself on the question ?

**Comment by autra** [comment]
Which type of UML diagram are you talking about?

Anyway, I don't think we should bother about that. In brief, no UML diagrams :-) Especially not the one you can auto-generate from the code (I guess I'm talking about package, class and object diagram. JS/UML generates class diagrams AFAIK). It bears no value to us, because we know the code already, and for object diagram, the documentation we'll generate from the code is better for the same information. For other devs, they will not want this format of information (too verbose, including to many irrelevant details), but instead they want to know where are the main piece to look at for a particular need. As for users, well UML has never targeted them, they won't be interested in such diagrams. They will need examples instead.

Also, I haven't used js/UML, but considering the nature of js, I'm doubtful it will be able to generate something clever... What results do you have using it on itowns?

I'm not against diagrams in general though, but I think we'll have better results if we use free-form, high-level diagrams to explain the structure of itowns (especially to welcome contributors), using nothing else but our common-sense (using yed or something similar). Nothing better than a human to explain to another human! Frankly, UML is too low-level, overkill and over-engineered for us.

**Comment by vcoindet** [comment]
Well I was thinking of class diagrams essentially.

Something wen't wrong with js/UML, so no result for now ! ;)
I agree, generate diagrams from the code (especially in js) is rarely a good thing, I was just thinking this might be a good starting point, but it can be messy too.

I think it would be great to have class diagrams to explain the structure of itowns to welcome contributors ! ;)

**Comment by Mkonini** [comment]
I agree, diagrams (UML genarated or hig level ones) explaining iTowns structure would be very helpful not only for new contibutors but also for all developpers because they allow to discuss about architectural choices.

**Comment by EricBoix** [comment]
As Martin Fawler puts it, [UML has many usage modes](https://martinfowler.com/bliki/UmlMode.html). [UML as sketch](https://martinfowler.com/bliki/UmlAsSketch.html) can prove to be  a valuable facilitator for project newbies that want to understand the structure while leaving out the details. A few manually derived architectural class/package UML sketches would be of great help IMVHO...

**Comment by vcoindet** [comment]
I made those diagramms, the first one is about the core part, the second about the process part and the third one is about the renderer part.
Can you tell me what do you think about it ? Thanks.

**MAJ : Diagrams are out of date**

![core](https://user-images.githubusercontent.com/16044646/33277042-a46d6778-d397-11e7-97dd-cdb26d19d7a3.png)
![process](https://user-images.githubusercontent.com/16044646/33277043-a482f7a0-d397-11e7-972a-f75b03b17e0d.png)
![renderer](https://user-images.githubusercontent.com/16044646/33277044-a497522c-d397-11e7-9cd8-702349c086e4.png)

**Comment by gchoqueux** [comment]
Diagrams are out of date

**Comment by gchoqueux** [comment]
see [Tools to generate UML](https://stackoverflow.com/questions/21696352/tools-to-generate-uml-diagrams-for-exisiting-classes-in-javascript)
