### ISSUE TITLE
QGis plugin for iTowns POC

### ISSUE THREAD

**Issue by gmaillet** [iTowns/itowns#406]
Creation of a QGis (v2 with Qt4) plugin based on iTowns.
This plugin will show and adapted version of the globe example (http://localhost:8080/examples/globe.html) in a docked widget with some features

1. center the 3D camera on the QGis Map (on demand)
2. center the QGis Map on the 3D view (on demand)
3. create QGis features in a vector layer from 3D pickGeoPosition in the 3D view
4. import geometry from a vector layer to the 3D view

a new branch (pluginQGIS) was created (during FOSS4G Code sprint),
Progression ( on https://github.com/iTowns/itowns/tree/pluginQGIS):
1. there are some visual side effects due to the shader simplification
2. elevation layers couldn't be loaded
3. features import in 3d view is not based on a true layer (like in WFS2_rebased) but is only an add on the scene
4. problems with coordinate system for imported features

**Comment by autra** [comment]
> Progression (859f827):

Maybe you can have a branch instead? We won't see it if you add more commits on top of this one. In the future, this plugin should have its own repo (which could be in itowns organization I think) and probably use npm to import releases of itowns.

> elevation layers couldn't be loaded

Do you have errors in the console? Otherwise it might be for the lack of float texture support.

Don't hesitate to open issues for any html/js errors you might have while using itowns. Work is not completely done to make itowns compatible with older engine.

**Comment by autra** [comment]
Ok I guess the branch is https://github.com/iTowns/itowns/tree/pluginQGIS. @vcoindet do you confirm it?

**Comment by gmaillet** [comment]
Yes, exactly. I have edited the initial description of the issue.

**Comment by gchoqueux** [comment]
@gmaillet  what is the outcome of this issue?
is it related with itowns support by Qt? (#75 )
