### ISSUE TITLE
Can't query crs

### ISSUE THREAD

**Issue by madalinul** [iTowns/itowns#463]
I am trying to add some custom wmtsc layers to a view with this code 

```
view.addLayer({
    customUrl: 'https://{a-c}.tile.openstreetmap.org/',
    networkOptions: { crossOrigin: 'anonymous' },
    type: 'color',
    protocol: 'wmtsc',
    id: 'osm_map',
    projection: 'EPSG:3857',
    options: {
    	tileMatrixSet: 'WGS84G',
    	mimetype: 'image/png',
    },
});

```
I am using the PlanarView like this

```
extent = new itowns.Extent(
    'EPSG:3857',
    146117.78532012575, 5385109.128666598, 177113.00028976472, 5420575.90979092);

// `viewerDiv` will contain iTowns' rendering area (`<canvas>`)
viewerDiv = document.getElementById('viewerDiv');

// Instanciate PlanarView*
view = new itowns.PlanarView(viewerDiv, extent, { renderer: renderer });
```

But I get this error: 'Can't query crs EPSG:3857 long/lat'.
Can someone help me?

**Comment by autra** [comment]
Hi! Thanks for reporting this issue :-)

However I can't reproduce :-( Can you copy-paste:
- the full stacktrace
- your html file? Or better: the link to your project if your code is open-source? Or alternatively, could you publish a test case allowing us to reproduce somewhere?

Can you tell me which itowns version are you using? (a commit hash is best).

Please note that if you need a globe, you can't currently use a TMS layer in another CRS than EPSG:4978...

Thanks!

**Comment by Jeremy-Gaillard** [comment]
Hi,

I think the issue is that you are trying to add a WMTS layer that is defined with globe coordinates to a planar view. iTowns does not automatically project images to the right reference system. Try with a WMTS that is defined in your local coordinate system.

On a related note, your extent definition seems strange: the bounds are in meters, while the coordinate system ([EPSG:3857](http://spatialreference.org/ref/sr-org/6864/)) uses latitude/longitude.

**Comment by autra** [comment]
Actually, I forgot to say that https://{a-c}.tile.openstreetmap.org/ seems to be a TMS server, not wmts... You should put `tms` in protocol (I made it to work in our orthographic example).

**Comment by madalinul** [comment]
@autra Can you share your code? I modified the layer type but still can't get it to work. Thanks for the help.

**Comment by autra** [comment]
@madalinul what are you exactly trying to achieve? Which version are you using?

Anyway, here is a not perfect, but working, example: https://gist.github.com/autra/493eb4d872e4938539f31332a7665459

(not perfect, because apparently PlanarControls does not work that well in the general case, and also because it does not seem to load higher zoom level).

**Comment by autra** [comment]
Forgot to say: this works with latest itowns master.

**Comment by madalinul** [comment]
@autra Thanks, that worked. But I have one more question.

1. If I use the wfs example with the PlanarView, and set a small extent with the tsm layer than the requsted tiles will be for the whole world not just my extent. Is there a way to fix this?

**Comment by peppsac** [comment]
> the requsted tiles will be for the whole world not just my extent. Is there a way to fix this?

This isn't supported yet for the TMS provider.
The changes required to support this are simple (see https://gist.github.com/peppsac/f7b549816ad10bf7ef4ad40953829fdc) so I'll probably open a PR soon to fix this.

Can you confirm that the linked patch works for you (it modifies the http://www.itowns-project.org/itowns/examples/orthographic.html demo)?
