### ISSUE TITLE
Color textures are wrong near Antartica

### ISSUE THREAD

**Issue by songsgroup** [iTowns/itowns#477]
i use chrome 60.0 64bit brows http://www.itowns-project.org/itowns/examples/globe.html ,the image look like this:
http://apps.dataxiu.com/others/itowns.png
## Your Environment

* itowns 2.0
* chrome 60.0 64bit
* window 10 
*  http://www.itowns-project.org/itowns/examples/globe.html

**Comment by autra** [comment]
Seem similar to https://github.com/iTowns/itowns/issues/346 (but this one was closed, maybe another bug then)


## Steps to Reproduce (for bugs)

1. Open http://www.itowns-project.org/itowns/examples/globe.html
2. rotate the globe to focus antartica
3. zoom

## Expected Behavior

Should display lower level in a coherent way, and stop at min zoom. Map should be continuous.

## Actual Behavior

See @songsgroup screenshot:

![here](http://apps.dataxiu.com/others/itowns.png)

Here is a gif of the whole process

![peekm1995y](https://user-images.githubusercontent.com/1576598/30388454-1774c32e-98b0-11e7-901a-b6cb593390bd.gif)

**Comment by songsgroup** [comment]
thanks.

**Comment by ogus** [comment]
This bug has been reproduced on the following configuration:
+ iTowns v2
+ Firefox v57.0.4
+ Ubuntu 16.04

![bug](https://user-images.githubusercontent.com/18139885/35146239-b2aa12ae-fd0a-11e7-95ca-1908cbad2dda.png)

Also, this bug has made the Web browser either unable to respond, or crash completely

![bug_detail](https://user-images.githubusercontent.com/18139885/35146380-191cd5ee-fd0b-11e7-8077-f42ed37174f3.png)

From the top window informations, it looks like too many tasks are executed at the same time

**Comment by autra** [comment]
> From the top window informations, it looks like too many tasks are executed at the same time

Not necessarily, the title can get a lot of ⌛ if there is an exception raised during mainloop execution (before this ⌛ gets removed).

**Comment by OlegYarko** [comment]
Any thoughts on how to fix this?
