### ISSUE TITLE
Improve Priority commands for faster tiles loading

### ISSUE THREAD

**Issue by nosy-b** [iTowns/itowns#50]

**Comment by qdnguyen** [comment]
We can improve Queue module to make it work with a sort function based on weigh, but my question is what kind of criterion will be used?

**Comment by nosy-b** [comment]
Least Recent Used go out. For the rest, last SSE to divide add top of stack. I'll test

**Comment by qdnguyen** [comment]
LRU is used only to cache elements, not to queue elements. 

You can use SSE like a criterion to load tiles.

ATTENTION: need a solution to avoid rearrangement of tiles every time when new tiles are integrated, otherwise we will have a problem of performance. Need some mecanic to integrated new tiles intelligently.

**Comment by qdnguyen** [comment]
I saw priority-queue in our project, even in our Queue.js we use priority, does it not work?

**Comment by gchoqueux** [comment]
see #136
