### ISSUE TITLE
Make release branches

### ISSUE THREAD

**Issue by gliegard** [iTowns/itowns#566]
A successful Git branching model
- Have a 'develop' branch (new features, new bugs)
- Have a release branch (bugfix process)
- Have a stable version tagged in master !

## Suggestion
We could use the famous "successful Git branching model"
It's explain in detail here
http://nvie.com/posts/a-successful-git-branching-model/

## Context
Actually, when we do a release, at the same time, we want to fix many bugs, and we add new features (add new potential bugs). For example, at the last minute, if a feature branch is merged with a bug, the release can be unstable.

## Solution

With the "successfull git branching model", in a release branch :
- We don't add new features (and new potential bugs)
- Only bugfixes
- The review process can be faster, because we don't want to refactor iTowns, just fix the bug. So the review process is less tense.

Then, when we consider that there is no bugs in the release branch anymore, we can send the code in the master, So the master is always considered stable !

On the other hand, in a feature branch, we can have a long review process, discuss about code philosophy, refactoring, api changes, all the things we are excellent at :)

I understand that this suggestion implies that we try to synchronize the release process (What features need to be in the next release ? When do we want the next release ?).

HTH

**Comment by tbroyer** [comment]
Git-flow is an over-engineered branching model (that there exists tooling around it rings a bell) that tries to solve non-issues (and creates new ones while doing so) by adding process/rules and some useless actions, clutters the history with unneeded merge commits, and changes conventions (`develop` vs. `master`) for no good reason.

A real, successful, and lighter-weight, branching model is [trunk based development](https://trunkbaseddevelopment.com/): always (always!) commit to `master`, create a release branch (aka stabilisation branch) when you want to prepare a release so you don't have to _freeze_ `master` (but do it as late as possible), cherry-pick fixes from `master` to the release branch.  
The **only** drawback is that a `git tag --contains $sha1` of the commit on `master` won't necessarily list the first release this commit shipped in if it was cherry-picked. This should be the exception though, and likely an acceptable tradeoff.    
If a freeze is deemed acceptable (depends heavily on how much time you take to test before actually releasing, i.e. the delta between “hey, let's cut a release” and the release tagging), then I'd argue releasing from `master` should even be preferred (so you only need to defer PR merges, and don't need to cherry-pick fixes). Choose a strategy on a case-by-case basis.

> For example, at the last minute, if a feature branch is merged with a bug, the release can be unstable.

If `master` was considered "stable enough" to be released as-is (i.e. release from trunk), and you merge a feature that you don't want to see in the release, it's still time to create a release branch from a point earlier in time so you don't have the new feature in the release.

> The review process can be faster, because we don't want to refactor iTowns, just fix the bug. So the review process is less tense.

If PRs clearly segregate bugfixes from new features, then bugfix reviews can (and generally should) be fast. And the "release manager(s)" (aka "merge meister(s)") is/are responsible for cherry-picking the commit to the release branch.

> Then, when we consider that there is no bugs in the release branch anymore, we can send the code in the master, So the master is always considered stable !

I'd argue that `master` (or even `develop` in git-flow) should always be "stable" (at least as stable as possible). But there really is no point in having a `master` branch like proposed in git-flow (at least I don't see any): there's `git tag --list` to list versions (use ` --sort=v:refname` or `--sort=creatordate` depending on what you want), so what's the point in having a branch where they're merged? (the article points at doing extra actions when something is pushed to this branch, but you can do the same based on tags alone)

**Comment by autra** [comment]
Thanks @gliegard to open this discussion

> Git-flow is an over-engineered branching model (that there exists tooling around it rings a bell) that tries to solve non-issues (and creates new ones while doing so) by adding process/rules and some useless actions, clutters the history with unneeded merge commits, and changes conventions (develop vs. master) for no good reason.

Couldn't say it better.

> A real, successful, and lighter-weight, branching model is trunk based development: always (always!) commit to master, create a release branch (aka stabilisation branch) when you want to prepare a release so you don't have to freeze master (but do it as late as possible), cherry-pick fixes from master to the release branch.

> If PRs clearly segregate bugfixes from new features, then bugfix reviews can (and generally should) be fast. And the "release manager(s)" (aka "merge meister(s)") is/are responsible for cherry-picking the commit to the release branch.

And that's incidentally quite what we are already doing (with the exception that I was tagging a commit instead of a branch, but that's exactly the same). Anyway, as I'm currently the self-appointed, unofficial "release manager", I can do this for the next release:  I can create a release branch early on (like 2-3 days before), and do this cherry-picking. That being said, it's only useful if people want to continue adding features in the meantime. In my experience, this has not happened in the last 2 releases. We're not that big of a project, it's not really disturbing to just wait for the tag creation before merging features...

So as a complementary (and better?) alternative, I'm *also* totally willing to make any number of bugfix releases you guys want (that includes the current version). So we could release without having the pressure of fixing minor bugs (for major and criticals, yes, we want them fixed before a release of course). After the release, whoever wants a fix just has to submit a PR against this release branch (making it clear in the PR description: the target branch is not very visible on github interface), and as soon as it is merged, I can create a new package with the new branch content. If it helps, I'd be happy to do it.

Btw, anyone can already create a 2.1.x branch from the last tag, and we can get started with a 2.1.1 bugfix releases *right now*, if they don't want to wait for 2.2 :-) 

One thing though:

> The review process can be faster, because we don't want to refactor iTowns, just fix the bug. So the review process is less tense.

Generally you're right. It's less tense because we don't care about formatting at all, and less about maintainability or code architecture. But you should be aware that this review is no less engaging than feature reviews, especially because you *really* don't want regression on a bugfix release (and yes, you can *also* introduce bugs in a bugfix PR).

Concerning the need for synchronizing the release process, I don't think we need one. We are currently following the [Release early, release often](https://en.wikipedia.org/wiki/Release_early,_release_often) philosophy, so:

> When do we want the next release ?

Currently, we more or less agree on a release every 2 months. So next one should be on November. I believe this is a good rhythm, but we can discuss that of course. We can also have extra releases from time to time just because! Not a problem.

> What features need to be in the next release ?

Whatever is currently in master (at the release branch creation time). What we should *not* do is precisely deciding of a set of features in next release, and release only when it is ready. It's stressful, painful and imo inefficient (technical debt anyone?). But most importantly: it is not an open-source process: external contributors cannot shape the project any more, only people on the "Council of the Gods", that decide this feature set, can.

**Comment by gmaillet** [comment]
This is just a fact: our master branch is not stable at all and it can't be used as it. 
Maybe we could done stronger reviews before merging in master, but it will slow down our innovation rythme.
If you think our project is too small and if you want to keep a very light process then, simply apply these minimal rules:
1. create a stabilisation branch from dev (as the new release candidate)
2. during two months (for example) you only apply fixes without new features on this branch (during this time new features can always be merged on the dev branch as we do now) 
3. Then, it becomes our new official stable release and we create the next release candidate from the dev branch.

It's far from perfect, but it's not so hard and it can help everybody. 
It will also force us to make a clearer difference between new feature PR and fix PR.

Without this minimal rules, every serious user of itowns will have to do it himself on his side and it's not efficient.
