### ISSUE TITLE
view.addLayer(url) support

### ISSUE THREAD

**Issue by mbredif** [iTowns/itowns#697]
The examples that use JSON layers currently follow the following pattern : 

```
function addLayerCb(layer) {
    return view.addLayer(layer);
}
promises.push(itowns.Fetcher.json('./layers/JSONLayers/Ortho.json').then(addLayerCb));
```

Should we support `view.addLayer('./layers/JSONLayers/Ortho.json')` directly which could return a promise to the layer ? That would simplify most of the examples !

**Comment by autra** [comment]
This is a pattern we use in our examples, but the real pattern is:
```js
view.addLayer(options)
```
We just store the options as json objects. It's a convenience. We did so notably because we cannot (yet) parse tileMatrixSets of WMTS servers. Maybe when this will be possible, we could simply drop these json?

But anyway, you are in no obligation to use this pattern.  You can do:
```js
view.addLayer({ /* json obj */ });
```

With webpack you can do
```
import orthoConfig from './layers/JSONLayers/ortho.json`;

//...

view.addLayer(ortho)
``` 

I'm not sure the view.addLayer(url) pattern is possible, because we need to specify what type of url it is most of the time (even with getCapabilities).

**Comment by mbredif** [comment]
Thanks for the overview.
What I propose is to have the possibility to do what you can currently do with webpack in projects that are not using webpack (such as the examples): 
``` view.addLayer('./layers/JSONLayers/ortho.json') ```
(I am referring to the json layer url, not the server url)
