### ISSUE TITLE
addLayer with wrong/undefined object blocks all next "addLayers" 

### ISSUE THREAD

**Issue by elias75015** [iTowns/itowns#768]
## Environment
* Version used:
Last "master" version of iTowns

* Browser Name and version:
Chrome 63

* Operating System and version (desktop or mobile):
Ubuntu 14 / Ubuntu 18

## Context

When you try an "addLayer" before globe initialization, with an incorrect layer object, a javascript error is raised (that's OK), but all "addLayer" done after are ignored.

Don't know if it's an expected behaviour, but in my opinion, it should not block everything.

- If the first layer you add is wrong, the globe will not have any layer displayed

- If you correctly add a layer before to add a "wrong" layer, the first layer will be correctly displayed and requested, but the layers added after the "wrong" addLayer will not be displayed.

## Steps to Reproduce

In the main iTowns sample page (index.html file).

### First scenario : no layer displayed

```
 var promises = [];
// wrong addLayer
globeView.addLayer("wrongObject");
// correct addLayer
promises.push(itowns.Fetcher.json('examples/layers/JSONLayers/Ortho.json').then(addLayerCb));
promises.push(itowns.Fetcher.json('examples/layers/JSONLayers/OrthosCRS.json').then(addLayerCb));
```

Result : No layers are added to the globe
![erroraddlayer](https://user-images.githubusercontent.com/6764800/40710409-da38c806-63f8-11e8-925b-0e3b2875e5d6.png)

### Second Scenario : layers not added
```
var promises = [];
// correct addLayer
promises.push(itowns.Fetcher.json('examples/layers/JSONLayers/Ortho.json').then(addLayerCb));
// wrong addLayer
globeView.addLayer("wrongObject");
// correct addLayer
promises.push(itowns.Fetcher.json('examples/layers/JSONLayers/ScanEX.json').then(addLayerCb));
promises.push(itowns.Fetcher.json('examples/layers/JSONLayers/Region.json').then(addLayerCb));
```

Result : only the first layer added (Ortho) is displayed.
![error2addlayer](https://user-images.githubusercontent.com/6764800/40710675-90778a1c-63f9-11e8-9803-d6c6b9b9cdec.png)

**Comment by autra** [comment]
> Don't know if it's an expected behaviour, but in my opinion, it should not block everything.

Completely agree, adding an invalid layer should in no way affect layers added after (or any layer actually).

**Comment by autra** [comment]
Actually reverting a bit what I just said. While it is true that one should still be able to add layer after such a failure, the problem is not that layer added later are not displayed, it is that *the code adding them is never executed* in your case, because you didn't catch the exception thrown by `addLayer`.

If you surround the faulty `addLayer` by a try/catch block, you'll see your other layer will work as usual.

Having `addLayer` throws an exception or not is a matter of choice. We have currently make these errors fatal to "fail fast".

**Comment by elias75015** [comment]
> Having addLayer throws an exception or not is a matter of choice. We have currently make these errors fatal to "fail fast".

Indeed. So do we assume the user has to catch the potential fatal errors ? In this case, maybe an iTowns example should show how to safely add layers (even if it's basic javascript) ?

**Comment by autra** [comment]
There is at least a documentation bug [here](http://www.itowns-project.org/itowns/API_Doc/View.html#addLayer) because it doesn't state that `addLayer` can throw.

But actually, now that I think about it, I think throwing here is too violent. As `addLayer` returns a promise, we should reject the returned promise in all error cases, not only when the error occurs in the async part of `addLayer`. That would be more consistent with this promise-based api pattern.

**Comment by zarov** [comment]
There are a few spot in the code where we could do a `Promise.reject` instead, but the problem is sometimes you have to go back really far in the code. But for the current issue, that could be done without too much hassle.

**Comment by zarov** [comment]
In fact this is the case here: we need to modify the `attach` method of `GeometryLayer`, but returning a `Promise.reject` to `addLayer` would mess some function signatures. What's your opinion here ?

**Comment by autra** [comment]
> we need to modify the attach method of GeometryLayer

I don't think so... I just wanted to wrap the whole `addLayer` body with something like
```js
return Promise.resolve().then(() => {
    // old body
});
```

or with 
```js
return new Promise((resolve, reject) => {
    // old body with return statements changed to resolve()
});
```
If we want to retain the synchronous part as synchronous. 

Actually, I should have opened a PR, it'd been faster than explaining :-) (doing it now)
