### ISSUE TITLE
Bad performance on Firefox

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#84]
The navigation is jerky on Firefox, but not on Chrome.

**Comment by nosy-b** [comment]
Help wanted? -> Use Chrome. ;)

On what OS, GPU, NativeGL or Angle...? 
Eventhough not a priority we should investigate on this yes, as Firefox is used by 17.5% of clients (Chrome 70.4%, ie 5.8% [http://www.w3schools.com/browsers/browsers_stats.asp](http://www.w3schools.com/browsers/browsers_stats.asp))

My experience:
 Win7 + Angle + TitanNvidia-> firefox much slower than chrome max 28 fps!
 Macos +  i5withHD4000 -> Firefox just a bit slower than chrome

**Comment by gcebelieu** [comment]
If it is to be used on a public web site, navigation shouldn't be jerky on firefox, chrome, safari, and... ie11 and edge 12+ .

**Comment by gchoqueux** [comment]
I executed itowns V2 on firefox nightly. The performance is better. This can be explained by multi-process. I think we should use the workers.

**Comment by gchoqueux** [comment]
IE is dead. itowns might work poorly on IE

**Comment by tbroyer** [comment]
FWIW, iTowns2 currently doesn't work on IE11 because the `Event` constructor is not supported. It's possible to shim the `CustomEvent` (e.g. https://github.com/necolas/dom-shims), but apparently not `Event`.  
Works in Edge (13) though.

(side note: I disagree that IE is dead; it's OK to only support IE11 and no previous version, but I think IE11 should be supported – if/when possible)
