### ISSUE TITLE
Layer

### ISSUE THREAD

**Issue by Jeremy-Gaillard** [iTowns/itowns#91]
In the current architecture, layers and data structures (such as quadtrees) share the same class. This causes some confusion and code weirdness.

We should clarify the layer concept and create a separate class for data structures.

**Comment by nosy-b** [comment]
Agreed.
We talked about creating a new Layer3D to handle 3D models & co.
But In fact I think we should not create a Layer3D class but rewrite a more generic and clean Layer class.

**Comment by peppsac** [comment]
>  But In fact I think we should not create a Layer3D class but rewrite a more generic and clean Layer class.

FWIW I'm working on this topic. Hopefully I'll have something to share before the end of the week.

**Comment by nosy-b** [comment]
@peppsac Good!
You can check what I tried a few months ago on the MobileMappingLayer eventhough it's not a good architecture it's a good case of separation between Material/Geometry and DataStructure.

**Comment by qdnguyen** [comment]
We should create a layer which is a THREE.object3D to be easly added to/removed from scene. 

Each class has a update function so that we can develop different methods for quadtree, octree, kd-tree, etc. 

This function is called/desactivated when layer is added to/removed from scene. 

Each layer should have a cache so that we can limit resource for each data type and easily integrate within view-dependent methods.

For quadtree, what kind of parameters do you need to update data?

For octree/motree i need only renderer and camera as input params of update function.

**Comment by Mkonini** [comment]
@qdnguyen My feeling is that you're trying to adapt the 3D layer to your previous developpments. 
We intend to develop a generic layer which can handle any 3D object, is that right?

**Comment by qdnguyen** [comment]
I want to say to LODs/hierarchical data (wmts/wms (quadtree), point cloud/mesh (octree) which need a view-dependent method to adjust level of details to adapt the data complexity according to its contribution to the rendered image. Not necessarily just the ones I did!

What kind of 3D data do you want to use with the 3D generic layer?

**Comment by gchoqueux** [comment]
move in #217
