### ISSUE TITLE
Globe example rendering incorrectly in mobile phone

### ISSUE THREAD

**Issue by augusttty** [iTowns/itowns#964]
## Enviorment
- Version used: 2.5.0(latest)
- Device: iphone 8plus (12.0.1)
- browser:  safari / wechat browser
## Behavior
- the gesture controls in mobile device are weird and hard to operate , whether rotating, zooming ,or tilting...
- the mapping layer over the globe is in disorder and displaying in pieces after initialization and comming operations.
## Others
- no error occurs in the console , excluding many warnings( as following screenshots )

And  i also saw the similar situations in  #654 and #309 ,but it seems that there is no solution yet.
Tks.
![_20181211144810](https://user-images.githubusercontent.com/22740321/49786227-08ba9980-fd5e-11e8-9024-69babed1bb3a.png)
![_20181211150540](https://user-images.githubusercontent.com/22740321/49786228-08ba9980-fd5e-11e8-9b5b-47da2dce5dee.png)
![_20181211150544](https://user-images.githubusercontent.com/22740321/49786230-08ba9980-fd5e-11e8-8ac8-93d1c1465488.jpg)

**Comment by zarov** [comment]
Concerning the controls: we don't have resources to currently work on mobile devices, and that's why controls are so buggy. I have no idea of the size of the work to do, but I would be very happy to see someone contribute on this.

Concerning the visual, it is a problem with the `DEPTH_BUFFER`. It can be reproduced on some computers (mine included) by disabling the hardware acceleration for the rendering. Unfortunately I am not yet aware of a solution to this problem.

**Comment by augusttty** [comment]
@zarov 
Thanks.
I am working on a 3d-indoor lightweight  map project using three.js ,  looking for a solution to intergrate to  the world map .  It is essential to working on the mobile phones  which  quering  the positioning service. 
I tried the cesium,but they can not be combined very well  ——  the three.js scene cannot be interactive.
And if there is no other solutions  i will try to fix the mobile controls , and keep watching itown's updates.
