### ISSUE TITLE
WMS source ignores "vendorSpecific" parameters (?)

### ISSUE THREAD

**Issue by SesticM** [iTowns/itowns#995]
It seems that WMS source ignores "vendorSpecific" parameters, here's the code:

```javascript
var paramsDOF = {
    url: 'http://192.168.1.7/geoserver/inova/wms',
    name: 'inova:dof_2012_02500_rs',
    projection: 'EPSG:4326',
    extent: [-90, 90, -45, 45],
    transparent: true,
    format: 'image/png8',
    vendorSpecific: {
        buffer: 4096,
        format_options: 'dpi:300;quantizer:octree',
        tiled: true,
    },
};

var sourceDOF = new itowns.WMSSource(paramsDOF);

var layerDOF = new itowns.ColorLayer('dof_2012_02500_rs', {
    source: sourceDOF,
});

view.addLayer(layerDOF);
```

And here's one of the resulting web requests:
`http://192.168.1.7/geoserver/inova/wms?SERVICE=WMS&REQUEST=GetMap&LAYERS=inova:dof_2012_02500_rs&VERSION=1.3.0&STYLES=&FORMAT=image/png8&TRANSPARENT=true&BBOX=-90.000000000,0.000000000,90.000000000,180.000000000&CRS=EPSG:4326&WIDTH=256&HEIGHT=256`

Or am I doing something wrong?

## Environment

* Version used: 2.6.1

**Comment by zarov** [comment]
Weird, I copypaste your code and it works (minus the network error), I got for example:
`http://192.168.1.7/geoserver/inova/wms?SERVICE=WMS&REQUEST=GetMap&LAYERS=inova:dof_2012_02500_rs&VERSION=1.3.0&STYLES=&FORMAT=image/png8&TRANSPARENT=true&BBOX=-90.000000000,-180.000000000,90.000000000,0.000000000&CRS=EPSG:4326&WIDTH=256&HEIGHT=256&buffer=4096&format_options=dpi:300;quantizer:octree&tiled=true`.

Are you sure that you are using the last version of iTowns ? You may have missed some build on your side ? Otherwise I don't really see how could this be caused.

**Comment by zarov** [comment]
I have the answer: this feature has been added after 2.6.1, so you'll need to wait for the next release to use it, sorry.

**Comment by SesticM** [comment]
Oh, that explains it all :-) Closing the ticket.
